"""add structured job description fields

Revision ID: 9feb722422df
Revises: add_resume_profile
Create Date: 2026-09-07 14:29:16.723491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9feb722422df'
down_revision: Union[str, Sequence[str], None] = 'add_resume_profile'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessments_candidate_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_job_description_id'), table_name='assessments')
    op.drop_table('assessments')
    op.add_column('job_descriptions', sa.Column('preferred_skills', sa.JSON(), nullable=True))
    op.add_column('job_descriptions', sa.Column('education_required', sa.JSON(), nullable=True))
    op.add_column('job_descriptions', sa.Column('responsibilities', sa.JSON(), nullable=True))
    op.add_column('job_descriptions', sa.Column('qualifications', sa.JSON(), nullable=True))
    op.add_column('job_descriptions', sa.Column('employment_type', sa.String(length=100), nullable=True))
    op.add_column('job_descriptions', sa.Column('structured_profile', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'structured_profile')
    op.drop_column('job_descriptions', 'employment_type')
    op.drop_column('job_descriptions', 'qualifications')
    op.drop_column('job_descriptions', 'responsibilities')
    op.drop_column('job_descriptions', 'education_required')
    op.drop_column('job_descriptions', 'preferred_skills')
    op.create_table('assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_description_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('technical_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('qa_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('coding_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('communication_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recommendation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('assessments_candidate_id_fkey')),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], name=op.f('assessments_job_description_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assessments_pkey'))
    )
    op.create_index(op.f('ix_assessments_job_description_id'), 'assessments', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_candidate_id'), 'assessments', ['candidate_id'], unique=False)
    # ### end Alembic commands ###
